#!/bin/sh

# script/dbdump: Dump the database to a file in `dumps/`.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ -n "$1" ]; then
  pg_dump --file="dumps/kitsuawards_$1_$(date -u +"%Y%m%d%H%M%S").sql" --inserts "kitsuawards_$1"
else
  pg_dump --file="dumps/kitsuawards_development_$(date -u +"%Y%m%d%H%M%S").sql" --inserts "kitsuawards_development"
fi
